// <auto-generated />
namespace Final_Project_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddBackgroundBoardTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBackgroundBoardTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202105171001097_AddBackgroundBoardTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
